- src/components/BlipSelect.vue
- src/components/Collection.vue
Modificações requisitadas pelo time do CS. A principal mudança é a exibição do quickreply na horizontal, com o uso das setas que existem no carrossel. Também mexi nessas setas pra tentar deixá-las mais proximas da borda, tanto no carrossel quanto no quickreply
> Slide reply

- src/components/BlipSelect.vue
O botão tava ficando no lugar errado quando o teto do Quick Reply ficava grande :)
> Adjusting button position

- src/App.vue
- src/components/BlipGroupCard.vue
- src/components/BlipSelect.vue
- src/components/DocumentSelect.vue
- src/components/Location.vue
- src/components/MediaLink/Audio.vue
- src/components/MediaLink/BlipFile.vue
- src/components/MediaLink/Image.vue
- src/components/MediaLink/Video.vue
- src/components/WebLink.vue
- src/styles/common.scss
Created middle position variant. Fixed radio input click-area bug. Added flexible position to editing states.
> Middle Position and fix of radio inputs

- src/App.vue
- src/components/BlipSelect.vue
- src/components/ChatState.vue
- src/components/DocumentSelect.vue
- src/components/Location.vue
- src/components/MediaLink/Audio.vue
- src/components/MediaLink/BlipFile.vue
- src/components/MediaLink/Image.vue
- src/components/MediaLink/Video.vue
- src/components/PlainText.vue
- src/components/RequestLocation.vue
- src/components/WebLink.vue
- src/mixins/baseComponent.js
- src/styles/common.scss
All blip cards now have a button to define metadata. This button will just execute the callback that opens the edit window.
> Added define metadata button. #115223

- src/components/BlipSelect.vue
- src/components/ChatState.vue
- src/components/Collection.vue
- src/components/DocumentSelect.vue
- src/components/Location.vue
- src/components/MediaLink.vue
- src/components/MediaLink/Audio.vue
- src/components/MediaLink/BlipFile.vue
- src/components/MediaLink/Image.vue
- src/components/MediaLink/Video.vue
- src/components/PlainText.vue
- src/components/RequestLocation.vue
- src/components/WebLink.vue
- src/styles/common.scss
Had to add the callback in the inner components.
Also changed some css to position the button.
> Fix inner callbacks for media link and collection

- src/components/MediaLink/Video.vue
Using 100% of screen height when user click on fullscreen option on video card
fix #151773
> fix(video): video fullscreen adjustment

- src/App.vue
- src/components/BlipCard.vue
- src/components/BlipGroupCard.vue
- src/components/PlainText.vue
- src/mixins/sanitizeHtml.js
Configure the rendering of the a tag on the blip card
> Configure render tag a

- src/components/PlainText.vue
- src/mixins/sanitizeHtml.js
- src/utils/misc.js
> fix(plain text component): encode 'a' tag as text

- src/components/MediaLink.vue
- src/components/MediaLink/BlipFile.vue
- src/components/MediaLink/Image.vue
Adding on-selected function on MediaLink for image and file
> Adding on-selected function on MediaLink

- src/components/Collection.vue
Fix incorrect chars length in carousel
> fix: incorrect chars length in carousel

- package-lock.json
- package.json
- src/App.vue
- src/components/BlipCard.vue
- src/components/BlipGroupCard.vue
- src/components/MediaLink.vue
- src/components/MediaLink/BlipFile.vue
- src/components/MediaLink/Image.vue
The property on-selected was being used on media cards and it generated a breaking change on blip-cards. It was created another property called on-media-selected to be used to handle media click
> Bugfix - add on media select property

- src/App.vue
Concat suffix bot with sequential ID if use this config
> feat(Ticket.vue): Concat suffix sequential ID if exists

- src/App.vue
- src/components/BlipCard.vue
Add missing translation option to components
> fix(directive): Add missing translate options

- README.md
feat(pencil): new update readme
> feat(pencil): new update readme

- azure-pipelines.yml
> feat(pencil): change tag UTP

- package.json
feat(pencil): change semantic-release
(set pre and post)
> feat(pencil): change semantic-release

- src/components/BlipGroupCard.vue
Set prop "translations" in blip-group-card, and by pass to blip-card
> Set prop "translations" in blip-group-card

- src/components/BlipGroupCard.vue
New prop translations in BlipGroupCard.vue
> feat(BlipGroupCard.vue): New prop translations in BlipGroupCard.vue

- package.json
I made a mistake and updated the package.json version. Now I have to roll back.
> fix(package-json): roll back the version.

- src/components/Ticket.vue
Fix the variables names inside the 'waitingMsg' and 'closedAttendantMsg' properties.
> fix(Ticket): fix variable name

- src/components/BlipSelect.vue
fixing build trailling white space error
> fix(blipselect): prevent close when visualizing finished thread 

- package-lock.json
- package.json
- src/components/BlipGroupCard.vue
Set date of last  message on messages group
> fix(BlipGroupCard): Set date of last  message on messages group

- src/App.vue
- src/utils/misc.js
Resolving a bug where emails with hyphens doesn't render correctly
> fix(PlainText): email regex pattern

- src/utils/misc.js
Reverts takenet/blip-cards-vue-components#105
> Revert "fix(PlainText): email regex pattern"

- src/utils/misc.js
fix a bug where emails with hyphens does not renders correct
> fix(PlainText): Fix email regex to accept hyphen

- src/utils/misc.js
Adding validation to generate a new blip-cards version
> fix(blipCards): add comments to validation

- src/components/MediaLink/Audio.vue
Audio speed feature
Add alt to img tags
Add playbackrate to audio file
Changing css
> Adding audio speed feature

- src/components/MediaLink/Audio.vue
**_Audio speed feature_**
- Add alt to img tags
- Add playbackrate to audio file
- changing css
> feat(blipCards): Audio speed feature

- README.md
Updating readme to explain how to commit and write pull requests.
> feat(blipCards): updating readme commit patterns

- src/components/BlipListCard.vue
including enable on remove button
> feat: Update BlipListCard

- src/components/Location.vue
Updating gmaps key to fix an incident where users can't open any maps location on blip-chat
> Updating gmaps key

- README.md
> fix: gmaps api and readme

- README.md
Added step by step to manually generate a version.
> Added step by step to manually generate a version

- src/App.vue
- src/components/ApplicationJSon.vue
- src/components/ApplicationJSon/MenuList.vue
- src/components/ApplicationJSon/MenuListPrompt.vue
- src/components/BlipCard.vue
- src/index.js
Creates Menu List component to show interactive Menu and options presented to client on Desk.
> Fix(MenuList): Creates Menu List component to show interactive Menu and options presented to client on Desk

- src/components/MediaLink/Image.vue
> fix: change to create version

- src/components/ReplyCard/InReplyTo/InReplyToBase.vue
- src/components/ReplyCard/ReplyCard.vue
Updating the reply message component removing the icon and reply text from it
> Feature(Component): Removing the icon and reply text from the reply message

- src/components/BlipCard.vue
- src/components/BlipGroupCard.vue
- src/components/UnsuportedContent.vue
Adds failed click icon to show the failed reason with callback function
> Feature(Component): Add failed click icon

- src/components/UnsuportedContent.vue
UnsupportdContent with long message without space broken ballon limits
> fix(UnsupportedContent component): Big message leaking ballon

- src/components/BlipCard.vue
- src/components/BlipGroupCard.vue
- src/components/MediaLink.vue
- src/components/MediaLink/Audio.vue
- src/components/MediaLink/BlipFile.vue
- src/components/MediaLink/Image.vue
- src/components/MediaLink/Video.vue
- src/utils/media.js
- A new property has been added to receive a document fetch function of type media-link:
- If the prop is received, the media will be fetched using the function, and a uri will be created pointing to the blob;
- Otherwise, the current behavior will be maintained, that is, it will continue using the link received in the document.
> Feature - Fetch media and create local blob uri

- src/components/BlipCard.vue
- src/utils/MediaLinkTypesConstants.js
- src/utils/MessageTypesConstants.js
Adding verification for media link subtypes. We currently don't have any supported subtypes, will be added in subsequent pull requests
> feat(blip-card): adding media link type check in replied message

- src/components/ReplyCard/Replied/RepliedWithMediaLink.vue
> fix(component): fix color

- src/components/InteractiveButton.vue
- src/components/MediaLink/Audio.vue
- src/components/ReplyCard/Replied/RepliedBase.vue
- src/components/ReplyCard/Replied/RepliedWithMediaLink.vue
- src/components/ReplyCard/ReplyCard.vue
Adjusting reply, Interactive Button and Media Link css components
> fix(css) - Feature/adjusting css rebranding and reply

- src/components/MediaLink/Video.vue
> fix(component): Loading DS in videos

- src/components/ApplicationJSon.vue
- src/components/ApplicationJSon/MenuList.vue
- src/components/ApplicationJSon/MenuListPrompt.vue
- src/components/InteractiveButton.vue
- src/components/MediaLink/BlipFile.vue
- src/styles/common.scss
fix(css) - fix color (font e background ) in complex types
> fix(css) - Feature/adjusting css rebranding

- src/components/ReplyCard/InReplyTo/InReplyToText.vue
- src/styles/common.scss
Fixing background color of replied message when right message bublle and color of icons
> fix(ReplyCard): replied message background color

- src/components/BlipGroupCard.vue
component identifier by messageId
> improvement(component): component identifier by messageId

- src/components/BlipGroupCard.vue
component identifier by messageId
> refactor(component): component identifier by messageId

- src/components/BlipGroupCard.vue
component identifier by messageId
> fix(component): component identifier by messageId

- src/components/BlipCard.vue
- src/components/BlipGroupCard.vue
- src/components/ConversationSummary.vue
- src/components/TicketConversationSummary.vue
- src/index.js
- src/utils/MessageTypesConstants.js
Adding conversation summary card
> fix(conversation-summary): adding conversation summary card

- src/components/BlipCard.vue
- src/components/ConversationSummary.vue
Adjusting conversation summary card
> fix(conversation-summary): adjusting conversation summary card 

- src/components/ConversationSummary.vue
fix(conversation-summary): adjusting conversation summary card
> fix(conversation-summary): adjusting conversation summary card

- src/components/ConversationSummary.vue
Fix CSS overwriting font-size on portal
> fix(component): Fix CSS overwriting font-size on portal

- src/components/TemplateContent/MediaContent/MediaContent.vue
Merge to retry generating bug fix release
Image fix:
> Fix:#568808 - Template message, image spacing fix

- package-lock.json
- package.json
- src/components/BlipCalls.vue
- src/components/BlipCallsEndCard.vue
- src/components/BlipCard.vue
- src/components/BlipGroupCard.vue
- Improvements on BlipCalls card
- Upgrade blip-ds package
> Feature - Blip Calls

- src/components/BlipCallsEndCard.vue
Update blip-ds version from 1.272.0 to 1.272.2
> build(package.json): Update blip-ds version

- src/App.vue
- src/components/BlipCard.vue
- src/components/CopyAndPaste.vue
- src/index.js
Creating a new component with which the user can click the copy button and the value will be in your clipboard.
Its type is defined as 'application/vnd.lime.copy-and-paste+json'.
The component is divided in two areas, one with texts that can describe what you are copying and the last one with the copy button.
The text part is divided in header, body and footer, but only the body is required.
As for the button you can edit its text and value to be copied.
There are two forms to edit, the first one is for the text are, and the second is for the button.
> Creating copy and paste component

- src/App.vue
- src/components/BlipCalls.vue
- src/components/BlipCallsEndCard.vue
- src/enums/blipCallsStatus.enum.js
- src/enums/blipCallsType.enum.js
- Changed blip calls component to use DialStatus and VideoStreamStatus
> improvement(blip-calls): change blip calls finishing message status

- src/components/BlipCallsEndCard.vue
> Feature - calls end message

- src/components/ApplicationJSon.vue
- src/components/BlipCallsVoiceRequest.vue
- src/index.js
Created a new card for send call request to customer
> Created new calls card

- package-lock.json
- package.json
- src/components/BlipCallsEndCard.vue
- src/components/BlipCallsVoiceRequest.vue
- src/enums/blipCallsStatus.enum.js
Fix to show audio or video recording only the provider is Mobcall
> feat: display media card according to provider

- src/components/BlipGroupCard.vue
Added external message identification to group and single cards, using the BlipCardDate component to unify where the date rules are
> #649293 - Added external message identification

- src/App.vue
- src/utils/externalMessages.js
We changed the external message parameter indicator from #externalMessage to externalMessage
> #649293 - fix(ExternalMessage): Changing the external message parameter

- src/components/BlipCallsEndCard.vue
This PR aims to show the download button when bubble of BlipCallsEndCard is in the right position.
> [Feature] #657057 - Download Recording of WhatsApp Calls

- src/components/BlipCallsEndCard.vue
This PR aims to fix style of anchor on download of BlipCallsEndCard.
> [Feature] #657057 - Fix Anchor Style on Download

- src/components/BlipGroupCard.vue
- Remove time in ticket messages  
- Fix message spacing
> Bugfix - Remove time in ticket messages and fix message spacing

- src/styles/common.scss
- src/utils/FormatTextUtils.js
basically the bold color of the font was not being displayed
> fix: bold color in bds-typo component

- package-lock.json
- package.json
- src/components/TemplateContent/TemplateContent.vue
- src/utils/FormatTextUtils.js
fix left and right bold color for bds-typo component
> Fix left and right bold color for bds-typo component

- src/components/ApplicationJSon.vue
- src/components/BlipCallsVoiceRequest.vue
Added edit options on calls request card
> #670845 - added edit options on calls request card

- src/components/BlipGroupCard.vue
- src/components/MediaLink/Audio.vue
Add possibility to scroll the screen to the element (audio)
> Audio transcription improvements

- src/components/BlipGroupCard.vue
This PR aims to check if document metadata is available before using it to assign group member properties.
> [Bugfix] #698715 - Undefined Document Metadata

- src/components/BlipCalls/BlipCallsPermissionRequest.vue
> [Feature] #734743 - Fix BlipCallsPermissionRequest divider

- src/commandExamples.js
- src/components/ReplyCard/InReplyTo/InReplyToAudio.vue
- src/components/ReplyCard/InReplyTo/InReplyToBase.vue
- src/components/ReplyCard/ReplyCard.vue
> fix(Audio component on reply): Fix time on audio reply

- src/components/MediaLink/Video.vue
Added preload metadata parameter to video html tag and added time anchor to video url
> #752819 - adding preload tag and time anchor

- package-lock.json
- package.json
- src/commandExamples.js
- src/components/BlipCard.vue
- src/components/BlipCardReply.vue
- src/components/Location.vue
- src/components/MediaLink.vue
- src/components/ReactionCard/InReactionTo/InReactionToBase.vue
- src/components/ReplyCard/InReplyTo/InReplyToActiveMessage.vue
- src/components/ReplyCard/InReplyTo/InReplyToAudio.vue
- src/components/ReplyCard/InReplyTo/InReplyToBase.vue
- src/components/ReplyCard/InReplyTo/InReplyToDocument.vue
- src/components/ReplyCard/InReplyTo/InReplyToImage.vue
- src/components/ReplyCard/InReplyTo/InReplyToLocation.vue
- src/components/ReplyCard/InReplyTo/InReplyToVideo.vue
- src/components/ReplyCard/Replied/RepliedBase.vue
- src/components/ReplyCard/ReplyCard.vue
- src/components/TemplateContent/TemplateContent.vue
- src/components/UnsuportedContent.vue
- src/utils/MessageTypesConstants.js
Ability to navigate through reply messages
> feat(Reply media - Actions): Navigation in messages by clicking on reply

- src/components/Location.vue
- src/styles/common.scss
Fix the problem where the edit and delete buttons, of components, were not appearing.
> #713221 - Fix editable deletable buttons

- src/components/BlipSelect.vue
Fix preview of  custom replies in Blip Desk Web.
> #781670 - Fix custom replies preview

- src/components/BlipCard.vue
- src/components/BlipGroupCard.vue
- src/components/MediaLink.vue
- src/components/MediaLink/Image.vue
In order to have more flexibility in the BlipImage behavior, we are adding a new function parameter that catches the click on an image to do a certain action. A new one was created so it does not interfere with the on-media-selected that already exists.
> feat(BlipImage): Adding new image selected handler

- package-lock.json
- src/components/BlipCalls/BlipCallsPermissionReply.vue
- src/components/BlipCard.vue
This PR aims to fix Vue warning in BlipCallsPermissionReply.
> [Feature] #789221 - BlipCallsPermissionReply Vue Warning

- src/components/PlainText.vue
> fix(readMore):797277-presentation-read-more-conversation-history

- src/components/Redirect.vue
This PR aims to improve code readability.
> [Feature] Code Readability

- src/components/BlipSelect.vue
> #872091 - Fixing menu text elipsis
